#include<iostream>
#include<vector>
#include<algorithm>
#include <unordered_map>
using namespace std;

// LeetCode 389. Find the Difference
// Given two strings s and t which consist of only lowercase letters.
// String t is generated by random shuffling string s and then adding one more letter at any position.
// Find the letter that was added in t.

class Solution { 
public:

    char findTheDifference(string s, string t) {
        vector<char> c (26,0);
        for(int i=0;i<s.length();i++){
            char ch = s[i];
            c[ch-'a']++;
        }

        for(int i=0;i<t.length();i++){
            char ch = t[i];
            c[ch-'a']--;
            if(c[ch-'a'] < 0){
                return ch;
            }
        }
        return 'a';
    }

};

int main() {

    string s = "abcd";
    string t = "abcde";
    Solution sol;
    cout<<sol.findTheDifference(s, t);

    return 0;
}


/*
  

/************************************************** C++ **************************************************/
//Approach-1
//T.C : Linear
//S.C : Extra space map
class Solution {
public:
    char findTheDifference(string s, string t) {
        unordered_map<char, int> mp;
        
        for(char &ch : s) {
            mp[ch]++;
        }
        
        for(char &ch : t) {
            mp[ch]--;
            
            if(mp[ch] < 0)
                return ch;
        }
        
        return 'a'; //send any random. It will never reach here
    }
};

//Approach-2 (Using Sum Difference)
//T.C : Linear
//S.C : constant
class Solution {
public:
    char findTheDifference(string s, string t) {
        int sum = 0;
        
        for (char &ch: t)
            sum += ch;
        
        for (char &ch: s)
            sum -=ch;
        
        return (char)sum;
    }
};


//Approach-3 (Using XOR property)
//T.C : Linear
//S.C : constant
class Solution {
public:
    char findTheDifference(string s, string t) {
        int XOR = 0;
        
        for (char &ch: t)
            XOR ^= ch;
        
        for (char &ch: s)
            XOR ^=ch;
        
        return (char)XOR;
    }
};


