#include <iostream>
using namespace std;
class A {

  // private:
public:
  int x;

public:
  A(int a) { this->x = a; }

  A(A &a) { // what is this? This is a copy constructor. It is a special
            // constructor that is used to create a new object as a copy of an
            // existing object. The copy constructor takes a reference to an
            // object of the same class as an argument and initializes the new
            // object with the values of the existing object. In this case, the
            // copy constructor takes a reference to an object of class A and
            // initializes the new object by copying the value of x from the
            // existing object.
    this->x = a.x;
  }

  int getX() { return x; }
};

int main() {
  A a(10);
  A b = a; // This line creates a new object b of class A and initializes it
           // with the value of object a.
  // This is done using the copy constructor, which is a special constructor
  // that is automatically generated by the compiler if not explicitly defined
  // by the programmer. The copy constructor takes a reference to an object of
  // the same class and creates a new object that is a copy of the original
  // object. In this case, since we have not defined a copy constructor for
  // class A, the compiler will generate a default copy constructor that simply
  // copies the value of x from object a to object b.

  b.x = 0;
  cout << b.getX() << endl;
  cout << a.getX() << endl; // 10, because a and b are different objects, and
                            // changing b does not affect a.

  a.x = 20;
  cout << b.getX() << endl; // 0, because a and b are different objects, and
                            // changing a does not affect b.
  cout << a.getX() << endl; // 20, because we changed the value of x in object a
                            // to 20, and it does not affect object b.

  A c = b; // This line creates a new object c of class A and initializes it
           // with the value of object b.
  // This is done using the copy constructor, which is a special constructor
  // that is automatically generated by the compiler if not explicitly defined
  // by the programmer. The copy constructor takes a reference to an object of
  // the same class and creates a new  object that is a copy of the original
  // object. In this case, since we have not defined a copy constructor for
  // class A, the compiler will generate a default copy constructor that simply
  // copies the value of x from object b to object c.

  cout << c.getX()
       << endl; // 0, because c is a copy of b, and b has the value of x as 0.
  cout << b.getX() << endl; // 0, because b has the value of x as 0, and c is a
                            // copy of b, so c also has the value of x as 0.
  cout << a.getX()
       << endl; // 20, because a has the value of x as 20, and changing a does
                // not affect b or c, which are different objects.

  return 0;
}